### ISSUE TITLE
Error: Job not requeued because: timed-out and not checkpointable. 

### ISSUE THREAD

**Issue by hadifar** [facebookresearch/cc_net#19]
When I execute:

`python -m cc_net -l fa`

It throws the following exception:

```
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.8/site-packages/submitit/core/job_environment.py", line 185, in checkpoint_and_try_requeue
    raise utils.UncompletedJobError(message)
submitit.core.utils.UncompletedJobError: Job not requeued because: timed-out and not checkpointable.
```

Here is the full log.err:

```
2021-01-20 22:08 INFO 20945:cc_net.process_wet_file - Parsed 1 / 16000 files. Estimated remaining time: 177.9h
2021-01-20 22:08 INFO 20945:root - Starting download of https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2019-09/segments/155024747>
2021-01-20 22:08 INFO 20945:root - Downloaded https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2019-09/segments/1550247479101.30/we>
2021-01-20 22:08 INFO 20945:cc_net.process_wet_file - Kept 41_939 documents over 44_039 (95.2%).
2021-01-20 22:08 INFO 20945:cc_net.process_wet_file - Parsed 2 / 16000 files. Estimated remaining time: 147.7h
2021-01-20 22:08 INFO 20945:root - Starting download of https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2019-09/segments/155024747>
submitit WARNING (2021-01-20 22:08:54,313) - Caught signal 10 on 8095a4502934: this job is timed-out.
2021-01-20 22:08 WARNING 20945:submitit - Caught signal 10 on 8095a4502934: this job is timed-out.
2021-01-20 22:08 INFO 20945:submitit - Job not requeued because: timed-out and not checkpointable.
2021-01-20 22:08 INFO 20945:root - Downloaded https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2019-09/segments/1550247479101.30/we>
submitit WARNING (2021-01-20 22:08:54,522) - Bypassing signal 15
submitit WARNING (2021-01-20 22:08:54,522) - Bypassing signal 15
2021-01-20 22:08 WARNING 20956:submitit - Bypassing signal 15
2021-01-20 22:08 WARNING 20957:submitit - Bypassing signal 15
2021-01-20 22:08 INFO 20945:Classifier - Processed 0 documents in 0.025h (  0.0 doc/s).
2021-01-20 22:08 INFO 20945:Classifier - Kept 0 docs over 0 (0.0%)
2021-01-20 22:08 INFO 20945:Classifier - Found 0 language labels: {}
2021-01-20 22:08 INFO 20945:where - Selected 0 documents out of 0 ( 0.0%)
submitit ERROR (2021-01-20 22:08:54,541) - Submitted job triggered an exception
2021-01-20 22:08 ERROR 20945:submitit - Submitted job triggered an exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 851, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/opt/conda/lib/python3.8/site-packages/submitit/core/submission.py", line 65, in submitit_main
    process_job(args.folder)
  File "/opt/conda/lib/python3.8/site-packages/submitit/core/submission.py", line 58, in process_job
    raise error
  File "/opt/conda/lib/python3.8/site-packages/submitit/core/submission.py", line 47, in process_job
```

**Comment by RORO-ML** [comment]
Same here, aswell with `--execution local` (no slurm cluster set up, debug mode works fine). When I use the test configuration it goes through, but without 4 parallel threads on the CPU. Can I adjust something to run it in parallel locally? Thanks :)

**Comment by hadifar** [comment]
I'm not sure what was the problem but with the following config file it will work:


`python -m cc_net --config config/myconfig.json`

Here is `myconfig.json`:

```
{
    "hash_in_mem": 2,
    "dump": "2019-09",
    "num_shards": 8,
    "lang_whitelist": ["fa"],
    "num_segments_per_shard": -1,
    "mine_num_processes": 1,
    "pipeline": [
        "dedup",
        "lid",
        "keep_lang",
        "split_by_segment"
    ],
    "execution": "debug",
    "target_size": "1GB",
    "output_dir": "fa_data2",
    "mined_dir": "fa_mined_by_segment2",
    "cache_dir": "fa_data2/wet_cache"
}
```

**Comment by hadifar** [comment]
@gwenzek Any update on this? I can only run it in `debug` mode. Would you please give me some hint, how can I run it in `local` mode? I have a single machine with 100 CPUs :)

**Comment by sidsvash26** [comment]
> I'm not sure what was the problem but with the following config file it will work:
> 
> `python -m cc_net --config config/myconfig.json`
> 
> Here is `myconfig.json`:
> 
> ```
> {
>     "hash_in_mem": 2,
>     "dump": "2019-09",
>     "num_shards": 8,
>     "lang_whitelist": ["fa"],
>     "num_segments_per_shard": -1,
>     "mine_num_processes": 1,
>     "pipeline": [
>         "dedup",
>         "lid",
>         "keep_lang",
>         "split_by_segment"
>     ],
>     "execution": "debug",
>     "target_size": "1GB",
>     "output_dir": "fa_data2",
>     "mined_dir": "fa_mined_by_segment2",
>     "cache_dir": "fa_data2/wet_cache"
> }
> ```

this works for me as well. thanks! Is it possible to download and run on only a small sample of the full data? Say (1 million documents) in one language? If yes, what would be the config for that look like?

**Comment by hadifar** [comment]
@sidsvash26  set `num_segments_pre_shard` to some value in above config (e.g., 10 instead of -1) .

**Comment by gwenzek** [comment]
> @gwenzek Any update on this? I can only run it in `debug` mode. Would you please give me some hint, how can I run it in `local` mode? I have a single machine with 100 CPUs :)

I think the issue is that the jobs are "timing out". The local executor kills the job is they took longer than expected. Can you increase the time outs ? There is no config for  that you will have to look at `mine.py`. 
Do you have a good ethernet connection ? this is likely to be the blocker rather than the cpu.

Also what are you trying to achieve ? It seems that you want  to run the full mining , which requires a lot of RAM and CPUs for dedup. If you want to reproduce, your command should look something  like : `python -m cc_net --conf reproduce --dump 2019-09 -l fa` (from memory, you'll need to double check)

**Comment by leezu** [comment]
Besides the `log.err` attached above, it may also be helpful to take a look at the `log.out`:

```
submitit INFO (2021-03-30 00:05:31,209) - Starting with JobEnvironment(job_id=15725, hostname=ip-172-31-91-229, local_rank=0(1), node=0(1), global_rank=0(1))
submitit INFO (2021-03-30 00:05:31,209) - Loading pickle: /home/ubuntu/src/cc_net/data/logs/15725_submitted.pkl
submitit INFO (2021-03-30 00:07:01,149) - Job has timed out. Ran 1 minutes out of requested 5 minutes.
submitit WARNING (2021-03-30 00:07:01,150) - Caught signal 15 on ip-172-31-91-229: this job is timed-out.
submitit INFO (2021-03-30 00:07:01,150) - Job not requeued because: timed-out and not checkpointable.
submitit ERROR (2021-03-30 00:07:01,156) - Submitted job triggered an exception
```

"Job has timed out. Ran 1 minutes out of requested 5 minutes" stands out..

**Comment by grzywada** [comment]
Is this happening because when executing on local cluster the timeout is not being set as the below is reached only with slurm?

    ex.update_parameters(
        name=name,
        timeout_min=int(timeout_hour * 60),
        mem_gb=mem_gb,
        cpus_per_task=cpus,
        slurm_array_parallelism=task_parallelism,
        **options,
    )

**Comment by styxjedi** [comment]
> Is this happening because when executing on local cluster the timeout is not being set as the below is reached only with slurm?
> 
> ```
> ex.update_parameters(
>     name=name,
>     timeout_min=int(timeout_hour * 60),
>     mem_gb=mem_gb,
>     cpus_per_task=cpus,
>     slurm_array_parallelism=task_parallelism,
>     **options,
> )
> ```

I believe this is the reason. I tried to add this line in `cc_net/execution.py` as L57 (after init ex):
``` python
ex.parameters['timeout_min'] = int(timeout_hour * 60)
```

Everything seems fine until now.

**Comment by chirico85** [comment]
@styxjedi, to the others and of course to you @gwenzek for the great job, thanks a lot for the solution.

`ex.parameters['timeout_min'] = int(timeout_hour * 60)`

made my day!

..
Well the code ran well with `lang_whitelist=["de"] ` in `REPRODUCE_CONFIG` and executing the following line:

`python3 -m cc_net --config_name reproduce --dump 2019-09 --num_segments_per_shard 10`

..at least the first part. 1600 bin-files were generated and saved. However, It appears that _hashes_shard in mine.py is causing some problem I cannot find out why, yet. See the following output:

```
Finished job 30259 (1599 / 1600). Hashed data/hashes/2019-09/1598.bin
Finished job 30274 (1600 / 1600). Hashed data/hashes/2019-09/1599.bin
1 / 1600 jobs failed while running _hashes_shard
Failed 26059 -> /mnt/f/cc_net/cc_net/data/logs/26059_0_log.err
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/f/cc_net/cc_net/__main__.py", line 18, in <module>
    main()
  File "/mnt/f/cc_net/cc_net/__main__.py", line 14, in main
    func_argparse.parse_and_call(cc_net.mine.get_main_parser())
  File "/home/user/.local/lib/python3.8/site-packages/func_argparse/__init__.py", line 72, in parse_and_call
    return command(**parsed_args)
  File "/mnt/f/cc_net/cc_net/mine.py", line 631, in main
    all_files = mine(conf)
  File "/mnt/f/cc_net/cc_net/mine.py", line 334, in mine
    hashes_groups = list(jsonql.grouper(hashes(conf), conf.hash_in_mem))
  File "/mnt/f/cc_net/cc_net/mine.py", line 263, in hashes
    ex(_hashes_shard, repeat(conf), *_transpose(missing_outputs))
  File "/mnt/f/cc_net/cc_net/execution.py", line 201, in custom_map_array
    raise Exception(message)
Exception: 1 / 1600 jobs failed while running _hashes_shard
```

Are you familiar with that? @gwenzek, your comment in https://github.com/facebookresearch/cc_net/issues/31#issuecomment-1002639245 might be a clue, since I did not install Slurm yet. If that may be the reason, is it possible to skip creating the bin files when I retry the process?

Best regards! 

edit:
Sorry, I found out now that hashing is skipped for already hashed files. By the way, I also saw that a bin was not created and only its temp form was available. Gonna retry building this bin and report. The next step would be installing slurm...

**Comment by cassie-cuihua** [comment]
@styxjedi, sorry ，I see that the code works after someone adds this sentence,
 ex.parameters['timeout_min'] = int(timeout_hour * 60)
but what I want to ask is, should I just copy the whole sentence or assign an exact number to timeout_hour. Because, after I added this sentence directly, I reported an error, there is no definition timeout_hour .

**Comment by Ajax-Yi** [comment]
> @styxjedi, to the others and of course to you @gwenzek for the great job, thanks a lot for the solution.
> 
> `ex.parameters['timeout_min'] = int(timeout_hour * 60)`
> 
> made my day!
> 
> .. Well the code ran well with `lang_whitelist=["de"] ` in `REPRODUCE_CONFIG` and executing the following line:
> 
> `python3 -m cc_net --config_name reproduce --dump 2019-09 --num_segments_per_shard 10`
> 
> ..at least the first part. 1600 bin-files were generated and saved. However, It appears that _hashes_shard in mine.py is causing some problem I cannot find out why, yet. See the following output:
> 
> ```
> Finished job 30259 (1599 / 1600). Hashed data/hashes/2019-09/1598.bin
> Finished job 30274 (1600 / 1600). Hashed data/hashes/2019-09/1599.bin
> 1 / 1600 jobs failed while running _hashes_shard
> Failed 26059 -> /mnt/f/cc_net/cc_net/data/logs/26059_0_log.err
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/mnt/f/cc_net/cc_net/__main__.py", line 18, in <module>
>     main()
>   File "/mnt/f/cc_net/cc_net/__main__.py", line 14, in main
>     func_argparse.parse_and_call(cc_net.mine.get_main_parser())
>   File "/home/user/.local/lib/python3.8/site-packages/func_argparse/__init__.py", line 72, in parse_and_call
>     return command(**parsed_args)
>   File "/mnt/f/cc_net/cc_net/mine.py", line 631, in main
>     all_files = mine(conf)
>   File "/mnt/f/cc_net/cc_net/mine.py", line 334, in mine
>     hashes_groups = list(jsonql.grouper(hashes(conf), conf.hash_in_mem))
>   File "/mnt/f/cc_net/cc_net/mine.py", line 263, in hashes
>     ex(_hashes_shard, repeat(conf), *_transpose(missing_outputs))
>   File "/mnt/f/cc_net/cc_net/execution.py", line 201, in custom_map_array
>     raise Exception(message)
> Exception: 1 / 1600 jobs failed while running _hashes_shard
> ```
> 
> Are you familiar with that? @gwenzek, your comment in [#31 (comment)](https://github.com/facebookresearch/cc_net/issues/31#issuecomment-1002639245) might be a clue, since I did not install Slurm yet. If that may be the reason, is it possible to skip creating the bin files when I retry the process?
> 
> Best regards!
> 
> edit: Sorry, I found out now that hashing is skipped for already hashed files. By the way, I also saw that a bin was not created and only its temp form was available. Gonna retry building this bin and report. The next step would be installing slurm...

Hi,do you fix that, i just met the same problem,thanks!
