### ISSUE TITLE
getpy version specified in setup.py no longer available

### ISSUE THREAD

**Issue by leezu** [facebookresearch/cc_net#24]
https://github.com/facebookresearch/cc_net/blob/bda555bd1cf1ee2e0b925363e62a61cd46c8b60d/setup.py#L52
but only v0.9.9-beta, v0.9.6, v0.2.0-alpha exist: https://github.com/atom-moyer/getpy/tags

This causes `cc_net` installation to fail:
```

Could not find a version that satisfies the requirement getpy@ git+https://github.com/gwenzek/getpy.git@v0.9.10-subset (from cc-net==1.0.0) (from versions: )
Cleaning up...
  Removing source in /tmp/pip-2x4sgis2-build
  Removing source in /tmp/pip-build-5smbzi07/fasttext
  Removing source in /tmp/pip-build-5smbzi07/kenlm
  Removing source in /tmp/pip-build-5smbzi07/psutil
  Removing source in /tmp/pip-build-5smbzi07/sacremoses
  Removing source in /tmp/pip-build-5smbzi07/sentencepiece
  Removing source in /tmp/pip-build-5smbzi07/submitit
No matching distribution found for getpy@ git+https://github.com/gwenzek/getpy.git@v0.9.10-subset (from cc-net==1.0.0)
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for getpy@ git+https://github.com/gwenzek/getpy.git@v0.9.10-subset (from cc-net==1.0.0)

```

**Comment by leezu** [comment]
Nevermind, it's just an issue due to outdated pip. `python3.7 -m pip install --upgrade pip` fixes it.
